### ISSUE TITLE
[Windows] `pnpm run setup` has errors

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2-development-environment#1]
```
C:\Users\Jan\Documents\prisma2-development-environment (master -> origin)
λ pnpm run setup
Scope: current workspace package
> prisma2-dev-environment@1.0.1 setup C:\Users\Jan\Documents\prisma2-development-environment
> npm i --no-package-lock && ts-node scripts/setup.ts

added 74 packages from 81 contributors and audited 162 packages in 6.69s
found 0 vulnerabilities

  setup Cloning/Pulling all three main repos +0ms
  setup ./.         git clone https://github.com/prisma/lift.git +3ms
  setup ./.         git clone https://github.com/prisma/photonjs.git +31ms
Cloning into 'lift'...
  setup ./.         git clone https://github.com/prisma/prisma2.git +32ms
Cloning into 'photonjs'...
Cloning into 'prisma2'...
remote: Enumerating objects: 147, done.
remote: Enumerating objects: 359, done.
remote: Counting objects: 100% (359/359)
remote: Compressing objects:   2% (2/92)
remote: Enumerating objects: 335, done.
remote: Compressing objects:  73% (153/209)remote: Compressing objects: 100% (92/92), done.
remote: Compressing objects: 100% (209/209), done.
remote: Counting objects: 100% (335/335), done.
remote: Compressing objects: 100% (142/142), done.
Receceiving objects:  46% (2360/5130), 964.01 KiB | 1.87 MiB/ssed 3066R eceiving objects: 100% (3213/3213), 636.01 KiB | 1.23 MiB/seiving objects: 100% (3213/3213), 987.32 KiB | 1.22 MiB/s, done.
Resolving deltas: 100% (2105/2105), done.01 KiB | 1.87 MiB/ss
remote: Total 5130 (delta 223), reused 248 (delta 189), pack-reused 4795R
Receiving objects: 100% (5130/5130), 2.07 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (3450/3450), done.
remote: Total 8871 (delta 221), reused 249 (delta 146), pack-reused 8512R
Receiving objects: 100% (8871/8871), 71.97 MiB | 5.66 MiB/s, done.
Resolving deltas: 100% (6160/6160), done.
  setup Installing dependencies, building packages +15s
  setup ./photonjs/packages/get-platform npm i --no-progress --no-package-lock +1ms
  setup ./photonjs/packages/fetch-engine npm i --no-progress --no-package-lock +23ms
  setup ./photonjs/packages/engine-core npm i --no-progress --no-package-lock +26ms
  setup ./photonjs/packages/photon npm i --no-progress --no-package-lock +33ms
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jan\AppData\Roaming\npm-cache\_logs\2019-11-21T12_49_31_182Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jan\AppData\Roaming\npm-cache\_logs\2019-11-21T12_49_31_191Z-debug.log
Error: Error running npm i --no-progress --no-package-lock in photonjs/packages/fetch-engine:Error: Command failed with exit code 1: npm i --no-progress --no-package-lock
    at makeError (C:\Users\Jan\Documents\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.3.0\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\Users\Jan\Documents\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.3.0\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at C:\Users\Jan\Documents\prisma2-development-environment\scripts\setup.ts:87:11
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\prisma2-development-environment\scripts\setup.ts:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jan\AppData\Roaming\npm-cache\_logs\2019-11-21T12_49_31_274Z-debug.log
npm WARN @prisma/get-platform@0.1.9 No repository field.

added 4 packages from 44 contributors and audited 4 packages in 2.766s
found 0 vulnerabilities

  setup ./photonjs/packages/get-platform yarn build +4s
yarn run v1.17.3
$ tsc -d
Done in 2.19s.
```

![image](https://user-images.githubusercontent.com/183673/69339641-1236cc00-0c66-11ea-9bb5-ea0d02d58789.png)
![image](https://user-images.githubusercontent.com/183673/69339658-1ebb2480-0c66-11ea-95fa-92e9c97ad83a.png)

Not sure if it is in a good state afterwards or not.

**Comment by janpio** [comment]
Following the instructions in the README indicates that not:

![image](https://user-images.githubusercontent.com/183673/69339945-bc165880-0c66-11ea-8cc1-b879cbe2ac6e.png)
![image](https://user-images.githubusercontent.com/183673/69339969-c7698400-0c66-11ea-8ef2-24560498099b.png)

**Comment by janpio** [comment]
Got further this time:

```
C:\Users\Jan\Documents
λ cd throwaway\

C:\Users\Jan\Documents\throwaway
λ git clone https://github.com/prisma/prisma2-development-environment
Cloning into 'prisma2-development-environment'...
remote: Enumerating objects: 300, done.
remote: Counting objects: 100% (300/300), done.
remote: Compressing objects: 100% (211/211), done.
Receiving objects:  89% (267/300)
Receiving objects: 100% (300/300), 364.11 KiB | 855.00 KiB/s, done.
Resolving deltas: 100% (174/174), done.

C:\Users\Jan\Documents\throwaway
λ cd prisma2-development-environment\

C:\Users\Jan\Documents\throwaway\prisma2-development-environment (master -> origin)
λ pnpm install
Scope: all 1 workspace packages
Only the root workspace package is going to have hoisted dependencies in node_modules
.                                        |  +88 +++++++++
Resolving: total 88, reused 80, downloaded 8, done

C:\Users\Jan\Documents\throwaway\prisma2-development-environment (master -> origin)
λ pnpm run setup
Scope: current workspace package
> prisma2-dev-environment@1.0.1 setup C:\Users\Jan\Documents\throwaway\prisma2-development-environment
> ts-node scripts/setup.ts

  setup Cloning/Pulling all three main repos +0ms
  setup ./.         git clone --depth=20 https://github.com/prisma/lift.git +2ms
  setup ./.         git clone --depth=20 https://github.com/prisma/photonjs.git +38ms
Cloning into 'lift'...
  setup ./.         git clone --depth=20 https://github.com/prisma/prisma2.git +42ms
Cloning into 'photonjs'...
Cloning into 'prisma2'...
remote: Enumerating objects: 397, done.
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (397/397), done.

remote: Compressing objects:   2% (4/160)
remote: Counting objects:  40% (166/413)
                                   Receiving objects:  13% (52/397)413/413), done.
Receiving objects:  10% (20/194)% (327/327), done.Receiving objects:   9% (18/194)
Rremote: Total 413 (delta 129), reused 216 (delta 75), pack-reused 0eceiving objects:  87% (360/413), 284.00 KiB | 549.00 KiB/s
Receiving objects: 100% (413/413), 355.09 KiB | 580.00 KiB/s, done.
Resolving deltas: 100% (129/129), done.(163/397), 372.00 KiB | 731.00 KiBs:  72% (93/129)
remote: Total 194 (delta 45), reused 110 (delta 24), pack-reused 0R
Receiving objects: 100% (194/194), 189.30 KiB | 217.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
Receiving objects:  80% (318/397), 780.00 Kiremote: Total 397 (delta 110), reused 228 (delta 74), pack-reused 0B | 769.00 KiB/s
Receiving objects: 100% (397/397), 861.64 KiB | 805.00 KiB/s, done.
Resolving deltas: 100% (110/110), done.
  setup Installing dependencies, building packages +3s
[
  [
    '@prisma/cli',
    '@prisma/generator-helper',
    '@prisma/ink-components',
    '@prisma/get-platform'
  ],
  [ '@prisma/fetch-engine' ],
  [ '@prisma/engine-core' ],
  [ '@prisma/sdk' ],
  [ '@prisma/photon' ],
  [ '@prisma/lift' ],
  [ '@prisma/introspection' ],
  [ 'prisma2' ]
]
  setup ./.         pnpm i -r --ignore-scripts +57ms
Scope: all 12 workspace packages
Only the root workspace package is going to have hoisted dependencies in node_modules
 ERROR  No matching version found for @prisma/photon@* inside the workspace
Resolving: total 55, reused 10, downloaded 37
  setup ./prisma2/cli/cli pnpm run build +10s
  setup ./prisma2/cli/generator-helper pnpm run build +23ms
  setup ./prisma2/cli/ink-components pnpm run build +46ms
  setup ./photonjs/packages/get-platform pnpm run build +53ms
Scope: current workspace package
> @prisma/cli@0.1.29 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\cli
> tsc -d

Scope: current workspace package
> @prisma/generator-helper@0.0.29 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\generator-helper
> tsc -d

Scope: current workspace package
> @prisma/ink-components@0.0.22 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\ink-components
> tsc -d

Scope: current workspace package
> @prisma/get-platform@0.1.23 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\photonjs\packages\get-platform
> tsc -d

src/utils.ts:1:20 - error TS2307: Cannot find module 'strip-indent'.

1 import dedent from 'strip-indent'
                     ~~~~~~~~~~~~~~


Found 1 error.

Scope: current workspace package
 ERROR  Command failed with exit code 2.
src/__tests__/parseDistro.ts:127:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

127 describe('parseDistro', () => {
    ~~~~~~~~

src/__tests__/parseDistro.ts:129:5 - error TS2552: Cannot find name 'test'. Did you mean 'tests'?

129     test(t.name, () => {
        ~~~~

  src/__tests__/parseDistro.ts:3:7
    3 const tests = [
            ~~~~~
    'tests' is declared here.

src/__tests__/parseDistro.ts:131:7 - error TS2304: Cannot find name 'expect'.

131       expect(actual).toBe(t.expect)
          ~~~~~~

src/__tests__/parseOpenSSLVersion.ts:16:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

Error: 16Error running  describe('parseOpenSSLVersion', () => {
pnpm run build   in  prisma2/cli/cli~~~~~~~~:

Error: Command failed with exit code 1: pnpm run build
    at makeError (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.4.0\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.4.0\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at C:\Users\Jan\Documents\throwaway\prisma2-development-environment\scripts\setup.ts:83:11
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\scripts\setup.ts:6:65)
src/__tests__/parseOpenSSLVersion.ts    at processTicksAndRejections (internal/process/task_queues.js:85:5):
18:5 - error TS2552: Cannot find name 'test'. Did you mean 'tests'?

18     test(t.name, () => {
       ~~~~

  src/__tests__/parseOpenSSLVersion.ts:3:7
    3 const tests = [
            ~~~~~
    'tests' is declared here.

src/__tests__/parseOpenSSLVersion.ts:20:7 - error TS2304: Cannot find name 'expect'.

20       expect(actual).toBe(t.expect)
         ~~~~~~


Found 6 errors.

Scope: current workspace package
 ERROR  Command failed with exit code 2.
src/components/BorderBox.tsx:1:19 - error TS2307: Cannot find module 'react'.

1 import React from 'react'
                    ~~~~~~~

src/components/BorderBox.tsx:2:21 - error TS2307: Cannot find module 'ink'.

2 import { Box } from 'ink'
                      ~~~~~

src/components/BorderBox.tsx:30:26 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

30       const width = this.props.width || layout.width
                            ~~~~~

src/components/BorderBox.tsx:31:27 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

31       const height = this.props.height || layout.height
                             ~~~~~

src/components/BorderBox.tsx:35:23 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

35           title: this.props.title,
                         ~~~~~

src/components/BorderBox.tsx:39:31 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

39           drawExtension: this.props.extension,
                                 ~~~~~

src/components/BorderBox.tsx:41:14 - error TS2339: Property 'setState' does not exist on type 'BorderBox'.

41         this.setState({ border, height, width })
                ~~~~~~~~

src/components/BorderBox.tsx:49:13 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

49     const { props } = this
               ~~~~~

src/components/BorderBox.tsx:51:31 - error TS2339: Property 'props' does not exist on type 'BorderBox'.

51     const extensionTop = this.props.extension ? -1 : 0
                                 ~~~~~

src/components/Divider.tsx:1:28 - error TS2307: Cannot find module 'ink'.

1 import { Box, Color } from 'ink'
                             ~~~~~

src/components/Divider.tsx:2:19 - error TS2307: Cannot find module 'react'.

2 import React from 'react'
                    ~~~~~~~

src/components/Divider.tsx:3:25 - error TS2307: Cannot find module 'string-width'.

3 import stringWidth from 'string-width'
                          ~~~~~~~~~~~~~~

src/components/drawBox.tsx:2:25 - error TS2307: Cannot find module 'cli-truncate'.

2 import cliTruncate from 'cli-truncate'
                          ~~~~~~~~~~~~~~

src/components/drawBox.tsx:3:25 - error TS2307: Cannot find module 'string-width'.

3 import stringWidth from 'string-width'
                          ~~~~~~~~~~~~~~

src/components/DummySelectable.tsx:1:46 - error TS2307: Cannot find module 'react'.

1 import React, { useContext, useEffect } from 'react'
                                               ~~~~~~~

src/components/ErrorBox.tsx:1:19 - error TS2307: Cannot find module 'react'.

1 import React from 'react'
                    ~~~~~~~

src/components/ErrorBox.tsx:2:28 - error TS2307: Cannot find module 'ink'.

2 import { Box, Color } from 'ink'
                             ~~~~~

src/components/InkLink.tsx:1:19 - error TS2307: Cannot find module 'react'.

1 import React from 'react'
                    ~~~~~~~

src/components/InkLink.tsx:2:26 - error TS2307: Cannot find module 'terminal-link'.

2 import terminalLink from 'terminal-link'
                           ~~~~~~~~~~~~~~~

src/components/inputs/Checkbox.tsx:1:38 - error TS2307: Cannot find module 'ink'.

1 import { Box, BoxProps, Color } from 'ink'
                                       ~~~~~

src/components/inputs/Checkbox.tsx:2:56 - error TS2307: Cannot find module 'react'.

2 import React, { useState, useContext, useEffect } from 'react'
                                                         ~~~~~~~

src/components/inputs/Checkbox.tsx:5:26 - error TS2307: Cannot find module 'figures'.

5 import figures = require('figures')
                           ~~~~~~~~~

src/components/inputs/InkTextInput.tsx:3:28 - error TS2307: Cannot find module 'ink'.

3 import { Color, Box } from 'ink'
                             ~~~~~

src/components/inputs/InkTextInput.tsx:4:44 - error TS2307: Cannot find module 'react'.

4 import React, { useEffect, useState } from 'react'
                                             ~~~~~~~

src/components/inputs/TextInput.tsx:1:28 - error TS2307: Cannot find module 'ink'.

1 import { Box, Color } from 'ink'
                             ~~~~~

src/components/inputs/TextInput.tsx:2:56 - error TS2307: Cannot find module 'react'.

2 import React, { useState, useContext, useEffect } from 'react'
                                                         ~~~~~~~

src/components/inputs/TextInput.tsx:7:26 - error TS2307: Cannot find module 'figures'.

7 import figures = require('figures')
                           ~~~~~~~~~

src/components/RadioButton.tsx:1:21 - error TS2307: Cannot find module 'figures'.

1 import figures from 'figures'
                      ~~~~~~~~~

src/components/RadioButton.tsx:2:28 - error TS2307: Cannot find module 'ink'.

2 import { Box, Color } from 'ink'
                             ~~~~~

src/components/RadioButton.tsx:3:56 - errorsrc/__tests__/generatorHandler.test.ts TS2307: :Cannot find module 'react'.

32:31 import React, { useState, useContext, useEffect } from 'react'
 -  error  TS2582:                                                        ~~~~~~~Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.



32src/components/Spinner.tsx describe('generatorHandler', () => {
:  1 :~~~~~~~~23

 - error TS2307: Cannot find module 'ink'.

1src/__tests__/generatorHandler.test.ts import { Color } from 'ink'
: 40 :                      ~~~~~3
 -
error TS2582: src/components/Spinner.tsxCannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

:402   test('parsing error', async () => {
:  24  -   ~~~~error

 TS2307: Cannot find module 'ink-spinner'.

src/__tests__/generatorHandler.test.ts2: import InkSpinner from 'ink-spinner'
44 : 11                       ~~~~~~~~~~~~~ -

error TS2304: Cannot find name 'expect'.

src/components/Spinner.tsx44:     await expect(generator.init()).rejects.toThrow(
3  : 19          ~~~~~~ -

error TS2307: src/__tests__/generatorHandler.test.tsCannot find module 'react'.

:348 import React from 'react'
: 3  -                   ~~~~~~~error

 TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

src/components/TabIndex.tsx48:   test('minimal-executable', async () => {
1  : 19  ~~~~ -

error TS2307: src/__tests__/generatorHandler.test.tsCannot find module 'react'.

:154 import React from 'react'
: 5  -                   ~~~~~~~error

 TS2304: Cannot find name 'expect'.

src/hooks/useStdin.ts54:     expect(manifest).toMatchInlineSnapshot(`
1  : 41    ~~~~~~ -

errorsrc/__tests__/generatorHandler.test.ts TS2307: :Cannot find module 'ink'.

721: import { useStdin as inkUseStdin } from 'ink'
5  -  error                                        ~~~~~ TS2304:

Cannot find name 'expect'.

72src/hooks/useStdin.ts     expect(() => generator.generate(stubOptions)).not.toThrow()
:  2 :    ~~~~~~19

 - errorsrc/__tests__/generatorHandler.test.ts TS2307: :Cannot find module 'react'.

762: import React from 'react'
3  -  error                  ~~~~~~~ TS2582:

Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

76   test('failing-executable', async () => {

Found 36 errors.

   ~~~~

src/__tests__/generatorHandler.test.ts:81:5 - error TS2304: Cannot find name 'expect'.

81     expect(generator.getManifest()).rejects.toThrow()
       ~~~~~~

src/__tests__/generatorHandler.test.ts:82:5 - error TS2304: Cannot find name 'expect'.

82     expect(generator.generate(stubOptions)).rejects.toThrow()
       ~~~~~~

src/GeneratorProcess.ts:2:23 - error TS2307: Cannot find module 'cross-spawn'.

2 import { spawn } from 'cross-spawn'
                        ~~~~~~~~~~~~~

src/GeneratorProcess.ts:6:30 - error TS2307: Cannot find module 'isbinaryfile'.

6 import { isBinaryFile } from 'isbinaryfile'
                               ~~~~~~~~~~~~~~

src/GeneratorProcess.ts:46:7 - error TS2532: Object is possibly 'undefined'.

46       this.child.on('exit', code => {
         ~~~~~~~~~~

src/GeneratorProcess.ts:50:7 - error TS2532: Object is possibly 'undefined'.

50       this.child.on('error', err => {
         ~~~~~~~~~~


Found 13 errors.

Scope: current workspace package
 ERROR  Command failed with exit code 2.
Scope: current workspace package
 ERROR  Command failed with exit code 2.



   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                 Update available! 4.3.0 → 4.3.3                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v4.3.3   │
   │                  Run pnpm i -g pnpm to update!                  │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯


C:\Users\Jan\Documents\throwaway\prisma2-development-environment (master -> origin)
λ
```

**Comment by janpio** [comment]
After upgrading `pnpm` I got a lot farther:

```
...

  setup ./prisma2/cli/introspection pnpm run build +8s                                                                                                                           
Scope: current workspace package                                                                                                                                                 
> @prisma/introspection@0.0.162 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\introspection                                                 
> tsc -d && chmod +x dist/bin.js                                                                                                                                                 
                                                                                                                                                                                 
                                                                                                                                                                                 
  setup ./prisma2/cli/prisma2 pnpm run build +6s                                                                                                                                 
Scope: current workspace package                                                                                                                                                 
> prisma2@2.0.0-alpha.374 build C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\prisma2                                                             
> pnpm run tsc && pnpm run ncc:download && rm -rf build && pnpm run ncc && sed -i.bak 's/env ts-node/env node/g' 'build/index.js' && rm -f build/index.js.bak && scripts/copy-run
ime.sh                                                                                                                                                                           
                                                                                                                                                                                 
Scope: current workspace package                                                                                                                                                 
> prisma2@2.0.0-alpha.374 tsc C:\Users\Jan\Documents\throwaway\prisma2-development-environment\prisma2\cli\prisma2                                                               
> tsc -d && cp src/capture-worker.js dist/capture-worker.js && scripts/copy-runtime-dist.sh                                                                                      
                                                                                                                                                                                 
'scripts' is not recognized as an internal or external command,                                                                                                                  
operable program or batch file.                                                                                                                                                  
Scope: current workspace package                                                                                                                                                 
 ERROR  Command failed with exit code 1.                                                                                                                                         
Scope: current workspace package                                                                                                                                                 
 ERROR  Command failed with exit code 1.                                                                                                                                         
Error: Error running pnpm run build in prisma2/cli/prisma2:Error: Command failed with exit code 1: pnpm run build                                                                
    at makeError (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.4.0\node_modules\execa\lib\error.js:56:11)      
    at handlePromise (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\node_modules\.pnpm\registry.npmjs.org\execa\3.4.0\node_modules\execa\index.js:114:26)     
    at processTicksAndRejections (internal/process/task_queues.js:85:5)                                                                                                          
    at C:\Users\Jan\Documents\throwaway\prisma2-development-environment\scripts\setup.ts:83:11                                                                                   
    at Generator.throw (<anonymous>)                                                                                                                                             
    at rejected (C:\Users\Jan\Documents\throwaway\prisma2-development-environment\scripts\setup.ts:6:65)                                                                         
    at processTicksAndRejections (internal/process/task_queues.js:85:5)                                                                                                          
                                                                                                                                                                                 
                                                                                                                                                                                 
C:\Users\Jan\Documents\throwaway\prisma2-development-environment (master -> origin)                                                                                              
λ                                                                                                                                                                                
```

**Comment by timsuchanek** [comment]
Please try to use the git bash on Windows, that should get you further, as we use bash commands a lot in our build scripts.
