### ISSUE TITLE
setup command: scripts/download.js: FetchError from prisma-builds.s3

### ISSUE THREAD

**Issue by charlex** [prisma/prisma2-development-environment#23]
This is likely due to my own network connection (heavy traffic usage in my building, I suspect). But just posting here in case you need to track weird issues like this, or catch the error and handle:

```
 ❯ pnpm run setup                                                    [14:08:54]
Scope: current workspace package
```

```
warning In order to use "@prisma/client", please install @prisma/cli. You can install it with "npm add -D @prisma/cli".
  setup ./prisma-client-js/packages/photon pnpm run download +749ms
Scope: current workspace package

> @prisma/client@2.0.0-alpha.1016 download /Users/xxxxxx/code/prisma2-development-environment/prisma-client-js/packages/photon
> node scripts/download.js

   (node:19332) UnhandledPromiseRejectionWarning: FetchError: request to https://prisma-builds.s3-eu-west-1.amazonaws.com/?list-type=2&prefix=master&continuation-token=xxxx_redacted_xxxxx failed, reason: read ETIMEDOUT
    at ClientRequest.<anonymous> (/Users/xxxxxx/code/prisma2-development-environment/node_modules/.pnpm/registry.npmjs.org/node-fetch/2.6.0/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:19332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by charlex** [comment]
What should be done after receiving this? Just run setup again?
